// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDOI_uAOskKRE69IqPsvU1PsB6qpkhsxpo',
    appId: '1:920745386501:web:e5139ccaa766a16e92b26c',
    messagingSenderId: '920745386501',
    projectId: 'actividad-14f16',
    authDomain: 'actividad-14f16.firebaseapp.com',
    storageBucket: 'actividad-14f16.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAU43oELAdEk4YtExkLTeBmxbrlXSbm2I8',
    appId: '1:920745386501:android:943c80d7f29af7c792b26c',
    messagingSenderId: '920745386501',
    projectId: 'actividad-14f16',
    storageBucket: 'actividad-14f16.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB0x9xOBJRRAAZ3JCxcT4MA7OxCYBY_-Jk',
    appId: '1:920745386501:ios:c73785114499f98192b26c',
    messagingSenderId: '920745386501',
    projectId: 'actividad-14f16',
    storageBucket: 'actividad-14f16.appspot.com',
    iosBundleId: 'com.example.actividad',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB0x9xOBJRRAAZ3JCxcT4MA7OxCYBY_-Jk',
    appId: '1:920745386501:ios:c73785114499f98192b26c',
    messagingSenderId: '920745386501',
    projectId: 'actividad-14f16',
    storageBucket: 'actividad-14f16.appspot.com',
    iosBundleId: 'com.example.actividad',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDOI_uAOskKRE69IqPsvU1PsB6qpkhsxpo',
    appId: '1:920745386501:web:6b3b16b161cee4f492b26c',
    messagingSenderId: '920745386501',
    projectId: 'actividad-14f16',
    authDomain: 'actividad-14f16.firebaseapp.com',
    storageBucket: 'actividad-14f16.appspot.com',
  );
}
